<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;

class BreedSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('breeds')->insert([         
            ['name' => 'Afegão', 'specie_id' => 1],
            ['name' => 'Affenpinscher', 'specie_id' => 1],
            ['name' => 'Airedale Terrier', 'specie_id' => 1],
            ['name' => 'Akita Americano', 'specie_id' => 1],
            ['name' => 'Akita Inu', 'specie_id' => 1],
            ['name' => 'Alano Espanhol', 'specie_id' => 1],
            ['name' => 'American Staffordshire Terrier', 'specie_id' => 1],
            ['name' => 'American Water Spaniel', 'specie_id' => 1],
            ['name' => 'Barbet', 'specie_id' => 1],
            ['name' => 'Basenji', 'specie_id' => 1],
            ['name' => 'Basset Azul da Gasconha', 'specie_id' => 1],
            ['name' => 'Basset Fulvo da Bretanha', 'specie_id' => 1],
            ['name' => 'Basset Hound', 'specie_id' => 1],
            ['name' => 'Beagle', 'specie_id' => 1],
            ['name' => 'Beagle Harrier', 'specie_id' => 1],
            ['name' => 'Bearded Collie', 'specie_id' => 1],
            ['name' => 'Bedlington Terrier', 'specie_id' => 1],
            ['name' => 'Bernese Mountain Dog', 'specie_id' => 1],
            ['name' => 'Bichon Bolonhês', 'specie_id' => 1],
            ['name' => 'Bichon Havanês', 'specie_id' => 1],
            ['name' => 'Bichon Frisé', 'specie_id' => 1],
            ['name' => 'Bichon Maltês', 'specie_id' => 1],
            ['name' => 'Bloodhound', 'specie_id' => 1],
            ['name' => 'Boiadeiro Australiano', 'specie_id' => 1],
            ['name' => 'Boiadeiro Bernês', 'specie_id' => 1],
            ['name' => 'Border Collie', 'specie_id' => 1],
            ['name' => 'Border Terrier', 'specie_id' => 1],
            ['name' => 'Borzoi', 'specie_id' => 1],
            ['name' => 'Boston Terrier', 'specie_id' => 1],
            ['name' => 'Boxer', 'specie_id' => 1],
            ['name' => 'Bull Terrier', 'specie_id' => 1],
            ['name' => 'Bulldog Inglês', 'specie_id' => 1],
            ['name' => 'Bulldog Francês', 'specie_id' => 1],
            ['name' => 'Bullmastiff', 'specie_id' => 1],
            ['name' => 'Cairn Terrier', 'specie_id' => 1],
            ['name' => 'Cane Corso', 'specie_id' => 1],
            ['name' => 'Cão de Água Português', 'specie_id' => 1],
            ['name' => 'Cão de Crista Chinês', 'specie_id' => 1],
            ['name' => 'Cão de Montanha dos Pirinéus', 'specie_id' => 1],
            ['name' => 'Cão lobo checoslovaco', 'specie_id' => 1],
            ['name' => 'Cão da Groenlândia', 'specie_id' => 1],
            ['name' => 'Caniche ou Poodle', 'specie_id' => 1],
            ['name' => 'Cavalier King Charles Spaniel', 'specie_id' => 1],
            ['name' => 'Chesapeake Bay Retriever', 'specie_id' => 1],
            ['name' => 'Chihuahua', 'specie_id' => 1],
            ['name' => 'Chow Chow', 'specie_id' => 1],
            ['name' => 'Cirneco do Etna', 'specie_id' => 1],
            ['name' => 'Cocker Spaniel Americano', 'specie_id' => 1],
            ['name' => 'Cocker Spaniel Inglês', 'specie_id' => 1],
            ['name' => 'Collie', 'specie_id' => 1],
            ['name' => 'Coton de Tuléar', 'specie_id' => 1],
            ['name' => 'Dachshund', 'specie_id' => 1],
            ['name' => 'Dálmata', 'specie_id' => 1],
            ['name' => 'Dandie Dinmont Terrier', 'specie_id' => 1],
            ['name' => 'Doberman', 'specie_id' => 1],
            ['name' => 'Dogue Alemão', 'specie_id' => 1],
            ['name' => 'Dogue ou Dogo Argentino', 'specie_id' => 1],
            ['name' => 'Dogue Canário', 'specie_id' => 1],
            ['name' => 'Dogue de Bordeaux', 'specie_id' => 1],
            ['name' => 'Elkhound Norueguês', 'specie_id' => 1],
            ['name' => 'Fila Brasileiro', 'specie_id' => 1],
            ['name' => 'Fox Terrier', 'specie_id' => 1],
            ['name' => 'Foxhound Inglês', 'specie_id' => 1],
            ['name' => 'Galgo Escocês', 'specie_id' => 1],
            ['name' => 'Galgo Irlandês', 'specie_id' => 1],
            ['name' => 'Golden Retriever', 'specie_id' => 1],
            ['name' => 'Gos d’Atura', 'specie_id' => 1],
            ['name' => 'Grande Boiadeiro Suiço', 'specie_id' => 1],
            ['name' => 'Greyhound', 'specie_id' => 1],
            ['name' => 'Grifo da Bélgica', 'specie_id' => 1],
            ['name' => 'Husky Siberiano', 'specie_id' => 1],
            ['name' => 'Jack Russel Terrier', 'specie_id' => 1],
            ['name' => 'King Charles', 'specie_id' => 1],
            ['name' => 'Komondor', 'specie_id' => 1],
            ['name' => 'Kuvasz', 'specie_id' => 1],
            ['name' => 'Labradoodle', 'specie_id' => 1],
            ['name' => 'Labrador Retriever', 'specie_id' => 1],
            ['name' => 'Laika', 'specie_id' => 1],
            ['name' => 'Lakeland Terrier', 'specie_id' => 1],
            ['name' => 'Leonberger', 'specie_id' => 1],
            ['name' => 'Lhasa Apso', 'specie_id' => 1],
            ['name' => 'Malamute do Alasca', 'specie_id' => 1],
            ['name' => 'Maltês', 'specie_id' => 1],
            ['name' => 'Mastife', 'specie_id' => 1],
            ['name' => 'Mastin dos Pirenéus', 'specie_id' => 1],
            ['name' => 'Mastin do Tibete', 'specie_id' => 1],
            ['name' => 'Mastin Espanhol', 'specie_id' => 1],
            ['name' => 'Mastín Napolitano', 'specie_id' => 1],
            ['name' => 'Norfolk Terrier', 'specie_id' => 1],
            ['name' => 'Norwich Terrier', 'specie_id' => 1],
            ['name' => 'Old English Sheepdog', 'specie_id' => 1],
            ['name' => 'Papillon', 'specie_id' => 1],
            ['name' => 'Pastor Alemão', 'specie_id' => 1],
            ['name' => 'Pastor Australiano', 'specie_id' => 1],
            ['name' => 'Pastor Belga', 'specie_id' => 1],
            ['name' => 'Pastor de Brie', 'specie_id' => 1],
            ['name' => 'Pastor dos Pirenéus de Cara Rosa', 'specie_id' => 1],
            ['name' => 'Pequeno Cão Leão', 'specie_id' => 1],
            ['name' => 'Pequinês', 'specie_id' => 1],
            ['name' => 'Perdigueiro', 'specie_id' => 1],
            ['name' => 'Pinscher miniatura', 'specie_id' => 1],
            ['name' => 'Pitbull', 'specie_id' => 1],
            ['name' => 'Podengo', 'specie_id' => 1],
            ['name' => 'Poodle', 'specie_id' => 1],
            ['name' => 'Pointer', 'specie_id' => 1],
            ['name' => 'Pug', 'specie_id' => 1],
            ['name' => 'Rhodesian Ridgeback', 'specie_id' => 1],
            ['name' => 'Rottweiler', 'specie_id' => 1],
            ['name' => 'Rough Collie', 'specie_id' => 1],
            ['name' => 'Sabueso', 'specie_id' => 1],
            ['name' => 'Saluki', 'specie_id' => 1],
            ['name' => 'Samoieda', 'specie_id' => 1],
            ['name' => 'São Bernardo', 'specie_id' => 1],
            ['name' => 'Sem Raça Definida', 'specie_id' => 1],
            ['name' => 'Scottish Terrier', 'specie_id' => 1],
            ['name' => 'Setter Irlandés', 'specie_id' => 1],
            ['name' => 'Shar-Pei', 'specie_id' => 1],
            ['name' => 'Shiba Inu', 'specie_id' => 1],
            ['name' => 'Shih Tzu', 'specie_id' => 1],
            ['name' => 'SilKy Terrier', 'specie_id' => 1],
            ['name' => 'Skye Terrier', 'specie_id' => 1],
            ['name' => 'Smooth Collie', 'specie_id' => 1],
            ['name' => 'Spitz Alemão', 'specie_id' => 1],
            ['name' => 'Staffordshire Bull Terrier', 'specie_id' => 1],
            ['name' => 'Tamaskan', 'specie_id' => 1],
            ['name' => 'Teckel', 'specie_id' => 1],
            ['name' => 'Terra Nova', 'specie_id' => 1],
            ['name' => 'Terrier Australiano', 'specie_id' => 1],
            ['name' => 'Terrier Escocês', 'specie_id' => 1],
            ['name' => 'Terrier Irlandês', 'specie_id' => 1],
            ['name' => 'Terrier Japonês', 'specie_id' => 1],
            ['name' => 'Terrier Negro Russo', 'specie_id' => 1],
            ['name' => 'Terrier Norfolk', 'specie_id' => 1],
            ['name' => 'Terrier Norwich', 'specie_id' => 1],
            ['name' => 'Terrier Tibetano', 'specie_id' => 1],
            ['name' => 'Tosa', 'specie_id' => 1],
            ['name' => 'Weimaraner', 'specie_id' => 1],
            ['name' => 'Welsh Corgi', 'specie_id' => 1],
            ['name' => 'West Highland White Terrier', 'specie_id' => 1],
            ['name' => 'Whippet', 'specie_id' => 1],
            ['name' => 'Xoloitzcuintli', 'specie_id' => 1],
            ['name' => 'Yorkshire Terrier', 'specie_id' => 1],
            ['name' => 'Abissínio', 'specie_id' => 2],
            ['name' => 'Angorá Turco', 'specie_id' => 2],
            ['name' => 'Asiático de Pêlo Semi-Longo', 'specie_id' => 2],
            ['name' => 'Azul Russo', 'specie_id' => 2],
            ['name' => 'Balinês', 'specie_id' => 2],
            ['name' => 'Bambino', 'specie_id' => 2],
            ['name' => 'Bicolor Oriental', 'specie_id' => 2],
            ['name' => 'Bengal', 'specie_id' => 2],
            ['name' => 'Bobtail americano', 'specie_id' => 2],
            ['name' => 'Bobtail japonês', 'specie_id' => 2],
            ['name' => 'Bombay', 'specie_id' => 2],
            ['name' => 'Burmês ou Birmanês', 'specie_id' => 2],
            ['name' => 'Burmila', 'specie_id' => 2],
            ['name' => 'California Spangled', 'specie_id' => 2],
            ['name' => 'Cingapura', 'specie_id' => 2],
            ['name' => 'Chartreux', 'specie_id' => 2],
            ['name' => 'Chausie', 'specie_id' => 2],
            ['name' => 'Colorpoint de Pêlo Curto', 'specie_id' => 2],
            ['name' => 'Cornish Rex', 'specie_id' => 2],
            ['name' => 'Curl Americano', 'specie_id' => 2],
            ['name' => 'Devon Rex', 'specie_id' => 2],
            ['name' => 'Donskoy', 'specie_id' => 2],
            ['name' => 'Dragon Li', 'specie_id' => 2],
            ['name' => 'Egeu', 'specie_id' => 2],
            ['name' => 'Exótico Shorthair', 'specie_id' => 2],
            ['name' => 'Gato de Bengala', 'specie_id' => 2],
            ['name' => 'Gato do Chipre', 'specie_id' => 2],
            ['name' => 'Gato Asiático', 'specie_id' => 2],
            ['name' => 'Gato Siberiano', 'specie_id' => 2],
            ['name' => 'Havana Marrom', 'specie_id' => 2],
            ['name' => 'Himalaio', 'specie_id' => 2],
            ['name' => 'Javanês', 'specie_id' => 2],
            ['name' => 'Korat', 'specie_id' => 2],
            ['name' => 'Khao Manee', 'specie_id' => 2],
            ['name' => 'Kurilian Bobtail', 'specie_id' => 2],
            ['name' => 'LaPerm', 'specie_id' => 2],
            ['name' => 'Levkoy Ucraniano', 'specie_id' => 2],
            ['name' => 'Lykoi', 'specie_id' => 2],
            ['name' => 'Maine Coon', 'specie_id' => 2],
            ['name' => 'Manx', 'specie_id' => 2],
            ['name' => 'Mau Árabe', 'specie_id' => 2],
            ['name' => 'Mau Egípcio', 'specie_id' => 2],
            ['name' => 'MinsKin', 'specie_id' => 2],
            ['name' => 'Mist Australiano', 'specie_id' => 2],
            ['name' => 'Munchkin', 'specie_id' => 2],
            ['name' => 'Nebelung', 'specie_id' => 2],
            ['name' => 'Norueguês da Floresta', 'specie_id' => 2],
            ['name' => 'Ocicat', 'specie_id' => 2],
            ['name' => 'Ojos Azules', 'specie_id' => 2],
            ['name' => 'Oregon Rex', 'specie_id' => 2],
            ['name' => 'Pêlo Curto Americano', 'specie_id' => 2],
            ['name' => 'Pêlo Curto Brasileiro', 'specie_id' => 2],
            ['name' => 'Pêlo Curto Europeu', 'specie_id' => 2],
            ['name' => 'Pêlo Curto Inglês', 'specie_id' => 2],
            ['name' => 'Pêlo Longo Inglês', 'specie_id' => 2],
            ['name' => 'Pêlo Curto Oriental', 'specie_id' => 2],
            ['name' => 'Pêlo Longo Oriental', 'specie_id' => 2],
            ['name' => 'Persa', 'specie_id' => 2],
            ['name' => 'Peterbald', 'specie_id' => 2],
            ['name' => 'Pixie-bob', 'specie_id' => 2],
            ['name' => 'Raas', 'specie_id' => 2],
            ['name' => 'Ragamuffin', 'specie_id' => 2],
            ['name' => 'Ragdoll', 'specie_id' => 2],
            ['name' => 'Rex Alemão', 'specie_id' => 2],
            ['name' => 'Sagrado da Birmânia', 'specie_id' => 2],
            ['name' => 'Savannah', 'specie_id' => 2],
            ['name' => 'Scottish Fold', 'specie_id' => 2],
            ['name' => 'Selkirk Rex', 'specie_id' => 2],
            ['name' => 'Serengeti', 'specie_id' => 2],
            ['name' => 'Siamês', 'specie_id' => 2],
            ['name' => 'Singapura', 'specie_id' => 2],
            ['name' => 'Snowshoe', 'specie_id' => 2],
            ['name' => 'Sokoke', 'specie_id' => 2],
            ['name' => 'Somali', 'specie_id' => 2],
            ['name' => 'Sphynx', 'specie_id' => 2],
            ['name' => 'Suphalak', 'specie_id' => 2],
            ['name' => 'Thai', 'specie_id' => 2],
            ['name' => 'Tiffany-Chantilly', 'specie_id' => 2],
            ['name' => 'Tonquinês', 'specie_id' => 2],
            ['name' => 'Toyger', 'specie_id' => 2],
            ['name' => 'Usuri', 'specie_id' => 2],
            ['name' => 'Van Turco', 'specie_id' => 2],
            ['name' => 'Wirehair Americano', 'specie_id' => 2],
            ['name' => 'Angorá', 'specie_id' => 3],
            ['name' => 'Anão Holandês', 'specie_id' => 3],
            ['name' => 'Argente Bleu', 'specie_id' => 3],
            ['name' => 'Argente Brun', 'specie_id' => 3],
            ['name' => 'Beveren', 'specie_id' => 3],
            ['name' => 'Branco De Florida', 'specie_id' => 3],
            ['name' => 'Britannia Petite', 'specie_id' => 3],
            ['name' => 'Coelho Alaska', 'specie_id' => 3],
            ['name' => 'Coelho Americano', 'specie_id' => 3],
            ['name' => 'Califórnia', 'specie_id' => 3],
            ['name' => 'Canela ou Cinnamom', 'specie_id' => 3],
            ['name' => 'Chinchila', 'specie_id' => 3],
            ['name' => 'D’Argente de Nata', 'specie_id' => 3],
            ['name' => 'D’Argente de Champagne', 'specie_id' => 3],
            ['name' => 'English Spot', 'specie_id' => 3],
            ['name' => 'Fuzzy Lop Americano', 'specie_id' => 3],
            ['name' => 'Gigante Britânico', 'specie_id' => 3],
            ['name' => 'Gigante De Checkered', 'specie_id' => 3],
            ['name' => 'Gigante Flemish ou Flamengo', 'specie_id' => 3],
            ['name' => 'Hare Belgas', 'specie_id' => 3],
            ['name' => 'Harlequin', 'specie_id' => 3],
            ['name' => 'Havana', 'specie_id' => 3],
            ['name' => 'Himalaio', 'specie_id' => 3],
            ['name' => 'Holandês', 'specie_id' => 3],
            ['name' => 'Hotot Anão', 'specie_id' => 3],
            ['name' => 'Jersey Wooly', 'specie_id' => 3],
            ['name' => 'Lilac', 'specie_id' => 3],
            ['name' => 'Lionhead', 'specie_id' => 3],
            ['name' => 'Lop', 'specie_id' => 3],
            ['name' => 'Lustrador', 'specie_id' => 3],
            ['name' => 'Mini Lop', 'specie_id' => 3],
            ['name' => 'Mini Rex', 'specie_id' => 3],
            ['name' => 'Mini Teddy', 'specie_id' => 3],
            ['name' => 'Nova Zelândia', 'specie_id' => 3],
            ['name' => 'Palomino', 'specie_id' => 3],
            ['name' => 'Pérola Do Fumo', 'specie_id' => 3],
            ['name' => 'Prata', 'specie_id' => 3],
            ['name' => 'Raposa De Prata', 'specie_id' => 3],
            ['name' => 'Raposa Suíça', 'specie_id' => 3],
            ['name' => 'Rex', 'specie_id' => 3],
            ['name' => 'Rhinelander', 'specie_id' => 3],
            ['name' => 'Sable Americano', 'specie_id' => 3],
            ['name' => 'Sati', 'specie_id' => 3],
            ['name' => 'Siberiano', 'specie_id' => 3],
            ['name' => 'Sussex', 'specie_id' => 3],
            ['name' => 'Tan', 'specie_id' => 3],
            ['name' => 'Thuringer', 'specie_id' => 3],
            ['name' => 'Viena', 'specie_id' => 3],
            ['name' => 'Agapornis', 'specie_id' => 4],
            ['name' => 'Arara', 'specie_id' => 4],
            ['name' => 'Cacatua', 'specie_id' => 4],
            ['name' => 'Calopsita', 'specie_id' => 4],
            ['name' => 'Canário', 'specie_id' => 4],
            ['name' => 'Papagaio', 'specie_id' => 4],
            ['name' => 'Periquito', 'specie_id' => 4],
        ]);
    }
}
